-- Generated by Mocodo 4.2.4

CREATE TABLE client (
  PRIMARY KEY (idClient),
  idClient VARCHAR(42) NOT NULL,
  nom      VARCHAR(42),
  prenom   VARCHAR(42),
  age      VARCHAR(42),
  ville    VARCHAR(42),
  email    VARCHAR(42),
  mdp      VARCHAR(42),
  image    VARCHAR(42),
  idAdmin  VARCHAR(42)
);

CREATE TABLE evenement (
  PRIMARY KEY (titre),
  titre    VARCHAR(42) NOT NULL,
  contenu  VARCHAR(42),
  image    VARCHAR(42),
  idClient VARCHAR(42) NOT NULL
);

ALTER TABLE evenement ADD FOREIGN KEY (idClient) REFERENCES client (idClient);
